### ISSUE TITLE
ability to use custom images in provisioning azure nodes

### ISSUE THREAD

**Issue by ricardolupo** [chef/chef-provisioning-azure#5]
- Creating rlupochefdemo02 with image rlcoreimagep01-20150209-623909 in East US...The virtual machine image source is not valid.

I'm currently able to provision a vm with an azure provided image.

**Comment by stuartpreston** [comment]
This is primarily because the project relies on the https://github.com/Azure/azure-sdk-for-ruby API and the current version of that (0.6.4) only has functionality that lists the public images, rather than including the user images too.

The fundamental problem seems to be there have not been significant updates to the SDK in line with the features that have been added to Azure.  This has caused lots of people (myself included) to take a fork of the code to get things working.  I do not know whether the chef-provisioning-azure project should follow suit.  Especially with things like Azure Resource Manager coming into mainstream usage.

Depending on how much you need it, feel free to ping me directly as I am working on making just enough changes in my fork to enable this scenario (create VM from user image).

**Comment by jkeiser** [comment]
@stuartpreston I am perfectly willing to take a dep on a fork if it gets us the functionality we need in the short term!  Got a link?

**Comment by stuartpreston** [comment]
@jkeiser Fair enough, in that case I'm working on it... will need a few days to line everything up - really want to get custom VM images, up to date VM image sizes, additional disks and windows (winrm) support into v1.0 if possible...

**Comment by stuartpreston** [comment]
As per the referenced PR, https://github.com/stuartpreston/azure-sdk-for-ruby has the relevant changes required to get the VM role added from User/captured image, and other goodness.

**Comment by jkeiser** [comment]
Will add the dep in a moment :)

**Comment by jkeiser** [comment]
@stuartpreston can you release your forked version to rubygems in the meantime (as stuartpreston-azure-ruby-sdk or something)?  Have you submitted a PR to Azure?

**Comment by jkeiser** [comment]
Merged the Gemfile change at 7f1fd59

**Comment by stuartpreston** [comment]
Ok to get things going I've released a forked version of stuartpreston-azure-sdk-for-ruby at https://rubygems.org/gems/stuartpreston-azure-sdk-for-ruby.  This means the Gemfile needs a change as I had to change the name.  PR coming up shortly.
